name: MySwiftUIApp

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: "14.0"

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.0"
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  TARGETED_DEVICE_FAMILY: "1,2"
  ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
  DEVELOPMENT_ASSET_PATHS: "\"MySwiftUIApp/Preview Content\""
  ENABLE_PREVIEWS: true
  GENERATE_INFOPLIST_FILE: true
  INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
  INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
  INFOPLIST_KEY_UILaunchScreen_Generation: true
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  SWIFT_EMIT_LOC_STRINGS: true
  CODE_SIGN_STYLE: "Automatic"
  DEVELOPMENT_TEAM: ""

targets:
  MySwiftUIApp:
    type: application
    platform: iOS
    sources:
      - path: MySwiftUIApp/App
      - path: MySwiftUIApp/Core
      - path: MySwiftUIApp/Data
      - path: MySwiftUIApp/Domain
      - path: MySwiftUIApp/Presentation
    resources:
      - path: MySwiftUIApp/Assets.xcassets
      - path: MySwiftUIApp/Preview Content
    info:
      path: MySwiftUIApp/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.MySwiftUIApp
      PRODUCT_NAME: "$(TARGET_NAME)"
      LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"

  MySwiftUIAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MySwiftUIAppTests
    dependencies:
      - target: MySwiftUIApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.MySwiftUIAppTests
      PRODUCT_NAME: "$(TARGET_NAME)"
      BUNDLE_LOADER: "$(TEST_HOST)"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MySwiftUIApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MySwiftUIApp"
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
      LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"
        - "@loader_path/Frameworks"

schemes:
  MySwiftUIApp:
    build:
      targets:
        MySwiftUIApp: all
        MySwiftUIAppTests: [test]
    run:
      target: MySwiftUIApp
      debugEnabled: true
    test:
      targets:
        - MySwiftUIAppTests
      debugEnabled: true
    analyze:
      target: MySwiftUIApp
    archive:
      target: MySwiftUIApp
